"""
Look up dict for deco rarity
"""
deco_lookup = {
  'Attack Jewel [1]':	              3,
  'Attack Jewel II [2]':	          4,
  'Attack Jewel III [3]':	          5,
  'Furor Jewel [2]':	              4,
  'Counterattack Jewel [3]':	      5,
  'Guardian Jewel [1]':	            3,
  'Guardian Jewel II [2]':	        4,
  'Guardian Jewel III [3]':	        5,
  'Guardian/Blaze Jwl [3]':	        7,
  'Guardian/Stream Jwl [3]':	      7,
  'Guardian/Frost Jwl [3]':	        7,
  'Guardian/Bolt Jwl [3]':	        7,
  'Guardian/Dragon Jwl [3]':	      7,
  'Guardian/Handicraft Jwl [3]':	  7,
  'Guardian/Ironwall Jwl [3]':	    7,
  'Flawless Jewel [2]':	            4,
  'Counter Jewel [2]':	            4,
  'Expert Jewel [1]':	              3,
  'Expert Jewel II [2]':	          4,
  'Expert Jewel III [3]':	          5,
  'Critical Jewel [1]':	            3,
  'Critical Jewel II [2]':	        4,
  'Critical Jewel III [3]':	        5,
  'Tenderizer Jewel [3]':	          5,
  'Draw Jewel [1]':	                3,
  'Draw Jewel II [2]':	            4,
  'Draw Jewel III [3]':	            5,
  'Mighty Jewel [2]':	              4,
  'Blaze Jewel [1]':	              3,
  'Blaze Jewel II [2]':	            4,
  'Blaze Jewel III [3]':	          5,
  'Blaze/Guardian Jewel [3]':	      6,
  'Blaze/Crit Elem Jwl [3]':	      6,
  'Blaze/Handicraft Jwl [3]':	      6,
  'Blaze/Rzr Sharp Jwl [3]':	      6,
  'Blaze/Precise Jewel [3]':	      6,
  'Blaze/Opener Jewel [3]':	        6,
  'Blaze/Bandolier Jwl [3]':	      6,
  'Blaze/Focus Jewel [3]':	        6,
  'Blaze/Enhancer Jwl [3]':	        6,
  'Blaze/KO Jewel [3]':	            6,
  'Blaze/Quickswitch Jwl [3]':	    6,
  'Blaze/Ironwall Jwl [3]':	        6,
  'Blaze/Shield Jewel [3]':	        6,
  'Stream Jewel [1]':	              6,
  'Stream Jewel II [2]':	          6,
  'Stream Jewel III [3]':	          6,
  'Stream/Guardian Jwl [3]':	      6,
  'Stream/Crit Elem Jwl [3]':	      6,
  'Stream/Handicraft Jwl [3]':	    6,
  'Stream/Rzr Sharp Jwl [3]':	      6,
  'Stream/Precise Jewel [3]':	      6,
  'Stream/Opener Jwl [3]':	        6,
  'Stream/Bandolier Jwl [3]':	      6,
  'Stream/Focus Jewel [3]':	        6,
  'Stream/Enhancer Jwl [3]':	      6,
  'Stream/KO Jewel [3]':	          6,
  'Stream/Quickswitch Jwl [3]':	    6,
  'Stream/Ironwall Jwl [3]':	      6,
  'Stream/Shield Jewel [3]':	      6,
  'Frost Jewel [1]':	              6,
  'Frost Jewel II [2]':	            6,
  'Frost Jewel III [3]':	          6,
  'Frost/Guardian Jwl [3]':	        6,
  'Frost/Crit Elem Jwl [3]':	      6,
  'Frost/Handicraft Jwl [3]':	      6,
  'Frost/Rzr Sharp Jwl [3]':	      6,
  'Frost/Precise Jewel [3]':	      6,
  'Frost/Opener Jewel [3]':	        6,
  'Frost/Bandolier Jwl [3]':	      6,
  'Frost/Focus Jewel [3]':	        6,
  'Frost/Enhancer Jwl [3]':	        6,
  'Frost/KO Jewel [3]':	            6,
  'Frost/Quickswitch Jwl [3]':	    6,
  'Frost/Ironwall Jwl [3]':	        6,
  'Frost/Shield Jewel [3]':	        6,
  'Bolt Jewel [1]':	                6,
  'Bolt Jewel II [2]':	            6,
  'Bolt Jewel III [3]':	            6,
  'Bolt/Guardian Jwl [3]':	        6,
  'Bolt/Crit Elem Jwl [3]':	        6,
  'Bolt/Handicraft Jwl [3]':	      6,
  'Bolt/Rzr Sharp Jwl [3]':	        6,
  'Bolt/Precise Jewel [3]':	        6,
  'Bolt/Opener Jewel [3]':	        6,
  'Bolt/Bandolier Jwl [3]':	        6,
  'Bolt/Focus Jewel [3]':	          6,
  'Bolt/Enhancer Jwl [3]':	        6,
  'Bolt/KO Jewel [3]':	            6,
  'Bolt/Quickswitch Jwl [3]':	      6,
  'Bolt/Ironwall Jewel [3]':	      6,
  'Bolt/Shield Jewel [3]':	        6,
  'Dragon Jewel [1]':	              6,
  'Dragon Jewel II [2]':	          6,
  'Dragon Jewel III [3]':	          6,
  'Dragon/Guardian Jwl [3]':	      6,
  'Dragon/Crit Elem Jwl [3]':	      6,
  'Dragon/Handicraft Jwl [3]':	    6,
  'Dragon/Rzr Sharp Jwl [3]':	      6,
  'Dragon/Precise Jewel [3]':	      6,
  'Dragon/Opener Jewel [3]':	      6,
  'Dragon/Bandolier Jwl [3]':	      6,
  'Dragon/Focus Jewel [3]':	        6,
  'Dragon/Enhancer Jwl [3]':	      6,
  'Dragon/KO Jewel [3]':	          6,
  'Dragon/Quickswitch Jwl [3]':	    6,
  'Dragon/Ironwall Jwl [3]':	      6,
  'Dragon/Shield Jewel [3]':	      6,
  'Venom Jewel [1]':	              3,
  'Venom Jewel II [2]':	            4,
  'Venom Jewel III [3]':	          5,
  'Paralyzer Jewel [1]':	          3,
  'Paralyzer Jewel II [2]':	        4,
  'Paralyzer Jwl III [3]':	        5,
  'Sleep Jewel [1]':	              3,
  'Sleep Jewel II [2]':	            4,
  'Sleep Jewel III [3]':	          5,
  'Blast Jewel [1]':	              3,
  'Blast Jewel II [2]':	            4,
  'Blast Jewel III [3]':	          5,
  'Crit Element Jewel [1]':	        3,
  'Crit Element Jewel II [2]':	    4,
  'Crit Elem Jwl III [3]':	        5,
  'Crit Elem/Blaze Jwl [3]':	      7,
  'Crit Elem/Stream Jwl [3]':	      7,
  'Crit Elem/Frost Jwl [3]':	      7,
  'Crit Elem/Bolt Jwl [3]':	        7,
  'Crit Elem/Dragon Jwl [3]':	      7,
  'Crit Elem/Handicraft Jwl [3]':	  7,
  'Crit Element/Precise Jwl [3]':	  5,
  'Crit Elem/KO Jewel [3]':	        7,
  'Crit Elem/Ironwall Jwl [3]':	    7,
  'Crit Status Jewel [1]':	        3,
  'Crit Status Jewel II [2]':	      4,
  'Crit Stat Jwl III [3]':	        5,
  'Crit Stat/Handicraft Jwl [3]':	  6,
  'Crit Stat/Precise Jwl [3]':	    6,
  'Crit Status/KO Jwl [3]':	        6,
  'Crit Stat/Ironwall Jwl [3]':	    6,
  'Charge Jewel [1]':	              3,
  'Charge Jewel II [2]':	          4,
  'Charge Jewel III [3]':	          5,
  'Charge/Handicraft Jwl [3]':	    5,
  'Charge/KO Jewel [3]':	          5,
  'Handicraft Jewel [1]':	          3,
  'Handicraft Jewel II [2]':	      4,
  'Handicraft Jwl III [3]':	        5,
  'Razor Sharp Jewel [1]':	        3,
  'Razor Sharp Jewel II [2]':	      4,
  'Rzr Sharp Jwl III [3]':	        5,
  'Rzr Sharp/Blaze Jwl [3]':	      7,
  'Rzr Sharp/Stream Jwl [3]':	      7,
  'Rzr Sharp/Frost Jwl [3]':	      7,
  'Rzr Sharp/Bolt Jwl [3]':	        7,
  'Rzr Sharp/Dragon Jwl [3]':	      7,
  'Rzr Sharp/Handicraft Jwl [3]':	  7,
  'Razor Sharp/KO Jwl [3]':	        7,
  'Rzr Sharp/Ironwall Jwl [3]':	    7,
  'Sharp Jewel [1]':	              3,
  'Sharp Jewel II [2]':	            4,
  'Sharp Jewel III [3]':	          5,
  'Mind\'s Eye Jewel [1]':	        3,
  'Mind\'s Eye Jewel II [2]':	      4,
  'Mind\'s Eye Jwl III [3]':	      5,
  'Blunt Jewel [1]':	              3,
  'Blunt Jewel II [2]':	            4,
  'Blunt Jewel III [3]':	          5,
  'Mastery Jewel [3]':	            5,
  'Forceshot Jewel [3]':	          5,
  'Pierce Jewel [3]':	              5,
  'Spread Jewel [3]':	              5,
  'Precise Jewel [1]':	            3,
  'Precise Jewel II [2]':	          4,
  'Precise Jewel III [3]':	        5,
  'Salvo Jewel [3]':	              5,
  'Opener Jewel [1]':	              3,
  'Opener Jewel II [2]':	          4,
  'Opener Jewel III [3]':	          5,
  'Opener/Blaze Jewel [3]':	        7,
  'Opener/Stream Jwl [3]':	        7,
  'Opener/Frost Jewel [3]':	        7,
  'Opener/Bolt Jewel [3]':	        7,
  'Opener/Dragon Jewel [3]':	      7,
  'Opener/Precise Jewel [3]':	      7,
  'Opener/Ironwall Jwl [3]':	      7,
  'Bandolier Jewel [1]':	          3,
  'Bandolier Jewel II [2]':	        4,
  'Bandolier Jewel III [3]':	      5,
  'Bandolier/Blaze Jwl [3]':	      7,
  'Bandolier/Stream Jwl [3]':	      7,
  'Bandolier/Frost Jwl [3]':	      7,
  'Bandolier/Bolt Jwl [3]':	        7,
  'Bandolier/Dragon Jwl [3]':	      7,
  'Bandolier/Precise Jwl [3]':	    7,
  'Bandolier/Ironwall Jwl [3]':	    7,
  'Trueshot Jewel [1]':	            3,
  'Trueshot Jewel II [2]':	        4,
  'Poisoncoat Jewel [2]':	          4,
  'Paracoat Jewel [3]':	            5,
  'Sleepcoat Jewel [3]':	          5,
  'Blastcoat Jewel [2]':	          4,
  'Draincoat Jewel [2]':	          4,
  'Defense Jewel [1]':	            3,
  'Protection Jewel [1]':           3,
  'Fire Res Jewel [1]':	            3,
  'Water Res Jewel [1]':	          3,
  'Thunder Res Jewel [1]':	        3,
  'Ice Res Jewel [1]':	            3,
  'Dragon Res Jewel [1]':	          3,
  'Antidote Jewel [1]':	            3,
  'Antipara Jewel [1]':	            3,
  'Pep Jewel [1]':	                3,
  'Def Lock Jewel [1]':	            3,
  'Steadfast Jewel [1]':	          3,
  'Suture Jewel [1]':	              3,
  'Escape Jewel [1]':	              3,
  'Antiblast Jewel [1]':	          3,
  'Perfume Jewel [1]':	            3,
  'Adapt Jewel [1]':	              3,
  'Medicine Jewel [1]':	            3,
  'Recovery Jewel [1]':	            3,
  'Survival Jewel [1]':	            3,
  'Physique Jewel [1]':	            3,
  'Refresh Jewel [2]':	            2,
  'Sprinter Jewel [1]':	            3,
  'Hungerless Jewel [1]':	          3,
  'Challenger Jewel [3]':	          5,
  'Throttle Jewel [3]':	            5,
  'Potential Jewel [2]':	          4,
  'Chain Jewel [3]':	              5,
  'Foray Jewel [3]':	              5,
  'Flayer Jewel [3]':	              5,
  'Focus Jewel [1]':	              3,
  'Focus Jewel II [2]':	            4,
  'Focus Jewel III [3]':	          5,
  'Focus/Blaze Jewel [3]':	        7,
  'Focus/Stream Jewel [3]':	        7,
  'Focus/Frost Jewel [3]':	        7,
  'Focus/Bolt Jwl [3]':	            7,
  'Focus/Dragon Jewel [3]':	        7,
  'Focus/Handicraft Jewel [3]':	    7,
  'Focus/Precise Jewel [3]':	      7,
  'Focus/KO Jewel [3]':	            7,
  'Enhancer Jewel [1]':	            3,
  'Enhancer Jewel II [2]':	        4,
  'Enhancer Jewel III [3]':	        5,
  'Enhancer/Blaze Jewel [3]':	      7,
  'Enhancer/Stream Jwl [3]':	      7,
  'Enhancer/Frost Jwl [3]':	        7,
  'Enhancer/Bolt Jewel [3]':	      7,
  'Enhancer/Dragon Jwl [3]':	      7,
  'Enhancer/Handicraft Jwl [3]':	  7,
  'Gambit Jewel [1]':	              3,
  'Gambit Jewel II [2]':	          4,
  'Gambit Jewel III [3]':	          5,
  'Gambit/Handicraft Jwl [3]':	    7,
  'Gambit/KO Jewel [3]':	          7,
  'Gambit/Ironwall Jwl [3]':	      7,
  'KO Jewel [1]':	                  3,
  'KO Jewel II [2]':	              4,
  'KO Jewel III [3]':	              5,
  'Drain Jewel [1]':	              3,
  'Drain Jewel II [2]':	            4,
  'Drain Jewel III [3]':	          5,
  'Artillery Jewel [1]':	          3,
  'Artillery Jewel II [2]':	        4,
  'Artillery Jewel III [3]':	      5,
  'Quickswitch Jewel [1]':	        3,
  'Quickswitch Jewel II [2]':	      4,
  'Quickswitch Jewel III [3]':	    5,
  'Quickswitch/Blaze Jwl [3]':	    7,
  'Quickswitch/Stream Jwl [3]':	    7,
  'Quickswitch/Frost Jwl [3]':	    7,
  'Quickswitch/Bolt Jwl [3]':	      7,
  'Quickswitch/Dragon Jwl [3]':	    7,
  'Quickswitch/Handicraft Jwl [3]':	7,
  'Quickswitch/KO Jwl [3]':       	7,
  'Quickswitch/Ironwall Jwl [3]':	  7,
  'Destroyer Jewel [2]':	          4,
  'Phoenix Jewel [2]':	            7,
  'Ambush Jewel [2]':	              4,
  'Sane Jewel [1]':	                5,
  'Sonorous Jewel [2]':	            4,
  'Sonorous/Attack Jwl [3]':	      5,
  'Sonorous/Expert Jwl [3]':	      5,
  'Sonorous/Draw Jwl [3]':	        5,
  'Sonorous/Handicraft Jwl [3]':	  5,
  'Sonorous/KO Jewel [3]':	        5,
  'Charge Up Jewel [2]':	          4,
  'Charge Up/Attack Jwl [3]':	      5,
  'Charge Up/Expert Jwl [3]':	      5,
  'Charge Up/Draw Jwl [3]':	        5,
  'Charge Up/Handicraft Jwl [3]':	  5,
  'Charge Up/KO Jewel [3]':	        5,
  'Flight Jewel [2]':	              4,
  'Flight/Attack Jwl [3]':	        5,
  'Flight/Expert Jewel [3]':	      5,
  'Flight/Draw Jewel [3]':	        5,
  'Flight/Handicraft Jwl [3]':	    5,
  'Growth Jewel [1]':	              3,
  'Poison Jewel [2]':	              3,
  'Poison/Attack Jewel [3]':	      6,
  'Poison/Expert Jwl [3]':	        6,
  'Poison/Draw Jewel [3]':	        6,
  'Poison/Handicraft Jwl [3]':	    6,
  'Poison/Precise Jwl [3]':	        6,
  'Poison/KO Jewel [3]':	          6,
  'Poison/Ironwall Jwl [3]':	      6,
  'Ironwall Jewel [1]':	            3,
  'Ironwall Jewel II [2]':	        4,
  'Ironwall Jewel III [3]':	        5,
  'Evasion Jewel [2]':	            5,
  'Jumping Jewel [2]':	            4,
  'Earplugs Jewel [2]':	            4,
  'Shield Jewel [1]':	              3,
  'Shield Jewel II [2]':	          4,
  'Shield Jewel III [3]':	          5,
  'Shield/Blaze Jewel [3]':	        6,
  'Shield/Stream Jewel [3]':	      6,
  'Shield/Frost Jewel [3]':	        6,
  'Shield/Bolt Jewel [3]':	        6,
  'Shield/Dragon Jwl [3]':	        6,
  'Shield/Handicraft Jwl [3]':	    6,
  'Shield/Ironwall Jwl [3]':	      6,
  'Sheath Jewel [1]':	              3,
  'Wind Resist Jewel [1]':	        3,
  'Footing Jewel [1]':	            3,
  'Brace Jewel [1]':	              3,
  'Intimidator Jewel [1]':	        3,
  'Gobbler Jewel [1]':	            3,
  'Magazine Jewel [1]':	            3,
  'Magazine Jewel II [2]':	        4,
  'Magazine/Attack Jwl [3]':	      5,
  'Magazine/Expert Jwl [3]':	      5,
  'Magazine/Draw Jwl [3]':	        5,
  'Magazine/Handicraft Jwl [3]':	  5,
  'Magazine/Ironwall Jwl [3]':	    5,
  'Mirewalker Jewel [1]':	          3,
  'Shockproof Jewel [1]':	          3,
  'Dive Jewel [1]':	                3,
  'Leap Jewel [1]':	                3,
  'Climber Jewel [1]':	            3,
  'Friendship Jewel [1]':	          3,
  'Maintenance Jewel [2]':	        4,
  'Bomber Jewel [1]':	              3,
  'Fungiform Jewel [2]':	          4,
  'Enduring Jewel [1]':	            3,
  'Satiated Jewel [1]':	            3,
  'Grinder Jewel [1]':	            3,
  'Grinder Jewel II [2]':	          4,
  'Grinder/Attack Jewel [3]':	      5,
  'Grinder/Expert Jewel [3]':	      5,
  'Grinder/Draw Jewel [3]':	        5,
  'Grinder/Handicraft Jwl [3]':	    5,
  'Grinder/KO Jewel [3]':	          5,
  'Grinder/Ironwall Jewel [3]':	    5,
  'Flash Jewel [1]':	              3,
  'Botany Jewel [1]':	              3,
  'Geology Jewel [1]':	            3,
  'Specimen Jewel [1]':	            3,
  'Ranger Jewel [1]':               3
}